- alias: 'Turn on Entrance when door is opened'
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_entrance_2
      to: "on"
  condition:
    - condition: template
      value_template: '{{ state_attr("sensor.daylight", "daylight") == "true" }}'
  action:
    - service: light.turn_on
      entity_id: light.inner_candle_entrance
