# Default integrations (substitute for default_config) 
cloud:
config:
frontend:
  themes: !include_dir_merge_named /config/lovelace/themes/
history:
logbook:
map:
person:
ssdp:
sun:
system_health:
updater:
# Text to speech
tts:
  - platform: google_translate

homeassistant:
  customize: !include_dir_merge_named /config/customize/

lovelace:
  mode: yaml

influxdb: !include influxdb.yaml

device_tracker: !include device_trackers.yaml
discovery: !include discovery.yaml
media_player: !include media_player.yaml
recorder: !include recorder.yaml
asuswrt: !include asuswrt.yaml
notify: !include notify.yaml
hacs: !include hacs.yaml
group: !include_dir_merge_named /config/group/
automation: !include_dir_merge_list /config/automations/
# script: !include_dir_merge_list /config/scripts/
script:
  disney_plus:
    sequence:
      - service: shell_command.app_change
zone: !include_dir_list /config/zones/
sensor: !include sensors.yaml
scene: !include_dir_merge_list /config/scenes/
input_boolean: !include input_booleans.yaml
input_datetime: !include input_datetimes.yaml
input_number: !include input_numbers.yaml
# shell_command: !include_dir_merge_list /config/shell_commands/
shell_command:
  app_change: '/usr/bin/curl -X POST http://192.168.1.200/DIAL/apps/com.sony.dtv.com.disney.disneyplus.com.bamtechmedia.dominguez.main.MainActivity'