# Default integrations (substitute for default_config) 
cloud:
config:
frontend:
history:
logbook:
map:
person:
ssdp:
sun:
system_health:
updater:
# Text to speech
tts:
  - platform: google_translate

homeassistant:
  customize: !include_dir_list /config/customize/

discovery: !include discovery.yaml
media_player: !include media_player.yaml
recorder: !include recorder.yaml
asuswrt: !include asuswrt.yaml
notify: !include notify.yaml
hacs: !include hacs.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include_dir_list /config/zones/