# Default integrations (substitute for default_config) 
cloud:
config:
frontend:
history:
logbook:
map:
person:
ssdp:
sun:
system_health:
updater:
# Text to speech
tts:
  - platform: google_translate

homeassistant:
  customize: !include_dir_merge_named /config/customize/

lovelace:
  mode: yaml

discovery: !include discovery.yaml
media_player: !include media_player.yaml
recorder: !include recorder.yaml
asuswrt: !include asuswrt.yaml
notify: !include notify.yaml
hacs: !include hacs.yaml
group: !include_dir_merge_named /config/group/
automation: !include_dir_merge_list /config/automations/
script: !include scripts.yaml
zone: !include_dir_list /config/zones/
sensor: !include sensors.yaml
scene: !include scenes.yaml
