# Default integrations (substitute for default_config) 
config:
frontend:
  themes: !include_dir_merge_named /config/lovelace/themes/
history:
logbook:
map:
person:
ssdp:
sun:
system_health:
updater:
mobile_app:

tts:
  - platform: google_translate

homeassistant:
  customize: !include_dir_merge_named /config/customize/

lovelace:
  mode: yaml

cloud:
  alexa: !include_dir_merge_named /config/alexa/

  #influxdb: !include influxdb.yaml
device_tracker: !include device_trackers.yaml
discovery: !include discovery.yaml
media_player: !include media_player.yaml
recorder: !include recorder.yaml
asuswrt: !include asuswrt.yaml
notify: !include notify.yaml
hacs: !include hacs.yaml
group: !include_dir_merge_named /config/group/
automation: !include_dir_merge_list /config/automations/
script: !include_dir_merge_named /config/scripts/
zone: !include_dir_list /config/zones/
sensor: !include sensors.yaml
scene: !include_dir_merge_list /config/scenes/
input_boolean: !include input_booleans.yaml
counter: !include counters.yaml
input_datetime: !include input_datetimes.yaml
input_number: !include input_numbers.yaml
shell_command: !include_dir_merge_named /config/shell_commands/
transmission: !include transmission.yaml
telegram_bot: !include telegram.yaml
light: !include light_group.yaml
alexa_media: !include alexa_media.yaml
blink: !include blink.yaml
