# default_config:

cloud:
config:
frontend:
history:
logbook:
map:
person:
ssdp:
sun:
system_health:
updater:

homeassistant:
  customize: !include customize.yaml

hacs:
  token: !secret hacs_token
  appdaemon: True
  python_script: True
  theme: True

# Text to speech
tts:
  - platform: google_translate

discovery:
  ignore:
    - google_cast
    - philips_hue
    - igd

media_player: !include media_player.yaml

recorder:
  purge_keep_days: 30
  purge_interval: 1
  #  db_url: sqlite:///mnt/usb-disk/home-assistant_v2.db

asuswrt:
  host: 192.168.1.1
  username: !secret asuswrt_user
  ssh_key: /config/asus_router

notify:
  - platform: html5
    name: Take Meter Readings
    vapid_pub_key: !secret html5_public_key
    vapid_prv_key: !secret html5_private_key
    vapid_email: !secret html5_email

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
