#- platform: systemmonitor
#  resources:
#    - type: memory_use_percent
#    - type: load_5m
#    - type: processor_use

- platform: time_date
  display_options:
    - 'time'

- platform: buienradar
  latitude: !secret buienradar_lat
  longitude: !secret buienradar_long
  monitored_conditions:
    - feeltemperature

- platform: template
  sensors:
    curl_resp:
      friendly_name: "Curl Response"
      value_template: "{{ 200 }}"
      icon_template: >-
      {% if is_state('sensor.curl_msg','200') %}
        mdi:email-send-outline
      {% elif is_state('sensor.curl_msg','201') %}
        mdi:email-check-outline
      {% elif is_state('sensor.curl_msg','400') or is_state('sensor.curl_msg','401') or is_state('sensor.curl_msg','403') %}
        mdi:email-off-outline
      {% else %}
        mdi:email-send-outline
      {% endif %}