- platform: time_date
  display_options:
    - 'time'

- platform: template
  sensors:
    curl_resp:
      friendly_name: "Gandi Curl Response"
      value_template: "200"
      attribute_templates:
        message: ""

- platform: template
  sensors:
    last_alexa:
      value_template: >
        {{ expand(states.group.echos) | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}

- platform: template
  sensors:
    pihole_disable_hour:
      entity_id: input_number.disable_pihole_duration_hours
      value_template: '{{ states("input_number.disable_pihole_duration_hours") | round(0) }}'
    pihole_disable_minutes:
      entity_id: input_number.disable_pihole_duration_mins
      value_template: '{{ states("input_number.disable_pihole_duration_mins") | round(0) }}'
    pihole_disable_seconds:
      entity_id: input_number.disable_pihole_duration_sec
      value_template: '{{ states("input_number.disable_pihole_duration_sec") | round(0) }}'
    pihole_disable_time:
      entity_id: 
        - sensor.pihole_disable_hour
        - sensor.pihole_disable_minutes
        - sensor.pihole_disable_seconds
      value_template: >
        {% if states("sensor.pihole_disable_hour")|length == 1 %}0{% endif %}
          {{ states("sensor.pihole_disable_hour") }}:
        {% if states("sensor.pihole_disable_minutes")|length == 1 %}0{% endif %}
          {{ states("sensor.pihole_disable_minutes"):
        {% if states("sensor.pihole_disable_seconds")|length == 1 %}0{% endif %}
          {{ states("sensor.pihole_disable_seconds") }}