- platform: time_date
  display_options:
    - 'time'

- platform: template
  sensors:
    curl_resp:
      friendly_name: "Gandi Curl Response"
      value_template: "200"

- platform: template
  sensors:
    vpn_status:
      friendly_name: "VPN Status Check"
      value_template: "new"