- platform: time_date
  display_options:
    - 'time'

- platform: buienradar
  latitude: !secret buienradar_lat
  longitude: !secret buienradar_long
  monitored_conditions:
    - feeltemperature

- platform: template
  sensors:
    curl_resp:
      friendly_name: "Gandi Curl Response"
      value_template: "200"

- platform: template
  sensors:
    vpn_error:
      friendly_name: "VPN Error Check"
      value_template: "off"