resources:
# Mini Media Player - installed via HACS
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
# Group Card - https://github.com/custom-cards/group-card
  - url: /community_plugin/group-card/group-card.js
    type: module
# Auto Entities - https://github.com/thomasloven/lovelace-auto-entities
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: module
# Text Input Row - https://github.com/gadgetchnnel/lovelace-text-input-row
  - url: /community_plugin/lovelace-text-input-row/lovelace-text-input-row.js
    type: js
# Multiple Entity Row - https://github.com/benct/lovelace-multiple-entity-row
  - url: /community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
# Button Entity Row - https://github.com/custom-cards/button-entity-row#using-state-icons
  - url: /community_plugin/button-entity-row/button-entity-row.js
    type: module

title: Main Lovelace
views:
  - !include /config/lovelace/views/view_home.yaml
  - !include /config/lovelace/views/view_bedroom.yaml
  - !include /config/lovelace/views/view_dining.yaml
  - !include /config/lovelace/views/view_kitchen.yaml
  - !include /config/lovelace/views/view_living.yaml
  - !include /config/lovelace/views/view_hallway.yaml
  - !include /config/lovelace/views/view_entrance.yaml
  - !include /config/lovelace/views/view_presence.yaml
  - !include /config/lovelace/views/view_sensors.yaml
  - !include /config/lovelace/views/view_automations.yaml