resources:
# Mini Media Player - installed via HACS
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
# Group Card - https://github.com/custom-cards/group-card
  - url: /community_plugin/group-card/group-card.js
    type: module

title: Main Lovelace
views:
  - !include /config/lovelace/views/view_home.yaml
  - !include /config/lovelace/views/view_bedroom.yaml
  - !include /config/lovelace/views/view_dining.yaml
  - !include /config/lovelace/views/view_kitchen.yaml
  - !include /config/lovelace/views/view_living.yaml
  - !include /config/lovelace/views/view_hallway.yaml
  - !include /config/lovelace/views/view_entrance.yaml
  - !include /config/lovelace/views/view_presence.yaml
  - !include /config/lovelace/views/view_automations.yaml