title: Automation
icon: mdi:auto-fix
path: automation
cards:
  - type: custom:auto-entities
    card:
      type: glance
      title: Automations
      show_header_toggle: false
    filter:
      include: 
        - domain: automation
  # - type: custom:group-card
  #   card:
  #     type: entities
  #     title: Automations
  #     show_header_toggle: false
  #   group: automation.all
