title: Automation
icon: mdi:auto-fix
path: automation
cards:
  - type: custom:group-card
    card:
      type: entities
      title: Automations
      show_header_toggle: false
    group: group.all_automations
