- alias: 'Trigger alarm when entrance is triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.entrance
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.no_one_home
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.alarm_notifications
    - delay:
        seconds: 60
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.no_one_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.disable_alarm
          state: 'off'
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.blink_home
    - service: script.turn_on
      entity_id: script.alarm
