- alias: 'Turn on Bedroom when bottom stairs sensor triggered'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_bottom_stairs_2
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
      - condition: state
        entity_id: light.hue_ambiance_3_bedroom
        state: 'off'
      - condition: template
        value_template: >
          '{{ as_timestamp(states.binary_sensor.motion_sensor_bottom_stairs_2.last_changed) > as_timestamp(states.binary_sensor.motion_sensor_top_stairs_2.last_changed) }}'
  action:
    - service: light.turn_on
      entity_id: light.hue_ambiance_3_bedroom
