- alias: 'Turn on Bedroom when bottom stairs sensor triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.bottom_stairs
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.hue_ambiance_3_bedroom