- alias: 'VPN check'
  trigger:
    - platform: time
      hours: '/1'
      minutes: 0
      seconds: 0
  action:
    - service: shell_command.check_vpn

- alias: 'VPN is not connected'
  trigger:
    - platform: state
      entity_id: sensor.vpn_error
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.vpn_notification_sent
      state: 'off'
  action:
    - service: notify.tim_phone_notifier
      data:
        title: "VPN is NOT Connected!!!"
        message: "Your VPN connection seems to be disabled"
    - service: homeassistant.turn_on
      entity_id: input_boolean.vpn_notification_sent