- alias: 'Turn on Dining and Hallway when top stairs sensor triggered'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_top_stairs_2
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.motion_sensor_bottom_stairs_2
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: group.dinning_room
    - service: light.turn_on
      entity_id: light.hue_bulb_hallway