- alias: 'Disable Alarm'
  trigger:
    - platform: state
      entity_id: input_boolean.disable_alarm
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.stop_voice_notification
    - service: homeassistant.turn_on
      entity_id: input_boolean.disable_alarm_camera
    - service: homeassistant.turn_on
      entity_id: input_boolean.disable_alarm_voice
    - service: homeassistant.turn_on
      entity_id: input_boolean.disable_alarm_lights
    - service: homeassistant.turn_on
      entity_id: input_boolean.disable_alarm_notification
    - service: automation.reload
      entity_id: all
    - delay:
        minutes: 1
    - service: homeassistant.turn_off
      entity_id: input_boolean.disable_alarm

- alias: 'Enable Alarms'
  trigger:
    - platform: state
      entity_id: input_boolean.disable_alarm
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.disable_alarm_camera
    - service: homeassistant.turn_off
      entity_id: input_boolean.disable_alarm_voice
    - service: homeassistant.turn_off
      entity_id: input_boolean.disable_alarm_lights
    - service: homeassistant.turn_off
      entity_id: input_boolean.disable_alarm_notification
