- alias: 'Disarm Blink Cameras'
  trigger:
    - platform: state
      entity_id: input_boolean.disable_alarm
      to: 'off'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.blink_home
