- alias: 'Turn on Hallway then Dining when entrance sensor triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.entrance
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
      - condition: or
        conditions:
          - condition: time
            after: '13:00:00'
            before: '23:30:00'
          - condition: time
            after: '07:00:00'
            before: '09:30:00'
  action:
    - service: light.turn_on
      entity_id: light.inner_candle_entrance
    - delay:
        seconds: 15
    - service: light.turn_on
      entity_id: light.hue_bulb_hallway
    - delay:
        seconds: 30
    - service: homeassistant.turn_on
      entity_id: group.dinning_room
    - service: light.turn_off
      entity_id: light.inner_candle_entrance
    - delay:
        seconds: 45
    - service: light.turn_off
      entity_id: light.hue_bulb_hallway

- alias: 'Turn off Dining after 3 min TV is on'
  trigger:
    - platform: state
      entity_id: media_player.mybraviatv
      to: 'on'
      for:
        minutes: 3
  action:
    - service: homeassistant.turn_off
      entity_id: group.dinning_room
