- alias: 'Turn on Hallway then Dining when entrance sensor triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.entrance
      to: 'on'
  condition:
    - condition: template
      value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
  action:
    - service: light.turn_on
      entity_id: light.inner_candle_entrance
    - delay:
        seconds: 15
    - service: homeassistant.turn_on
      entity_id: group.hallway
    - delay:
        seconds: 30
    - service: homeassistant.turn_off
      entity_id: input_boolean.no_one_home
    # - service: homeassistant.turn_on
    #   entity_id: group.dining_room
    - service: script.turn_on_dining
    - service: light.turn_off
      entity_id: light.inner_candle_entrance
    - delay:
        seconds: 45
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.storage
          state: 'off'
          for:
            minutes: 4
    - service: homeassistant.turn_off
      entity_id: group.hallway

- alias: 'Turn off Dining after 3 min TV is on'
  trigger:
    - platform: state
      entity_id: media_player.mybraviatv
      to: 'on'
      for:
        minutes: 3
  action:
    # - service: homeassistant.turn_off
    #   entity_id: group.dining_room
    - service: script.turn_off_dining
