- alias: 'Turn on Hallway then Dining when entrance sensor triggered'
  mode: restart
  trigger:
    - platform: state
      entity_id: input_boolean.entrance
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
  action:
    - service: script.turn_on_entrance
    - delay:
        seconds: 10
    - condition: state
      entity_id: input_boolean.no_one_home
      state: 'off'
    - service: script.turn_on_hallway
    - condition: state
      entity_id: input_boolean.asleep
      state: 'off'
    - delay:
        seconds: 10
    - service: script.turn_on_dining
    - delay:
        minutes: 2
    - service: script.turn_off_entrance
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.storage
          state: 'off'
          for:
            minutes: 1
    - service: script.turn_off_hallway
    - delay:
        minutes: 3
    - condition: state
      entity_id: media_player.mybraviatv
      state: 'on'
    - service: script.turn_off_dining


- alias: 'Turn off Dining after 3 min TV is on'
  trigger:
    - platform: state
      entity_id: media_player.mybraviatv
      to: 'on'
      for:
        minutes: 3
  action:
    - service: script.turn_off_dining
