- alias: 'Turn on Entrance when door is opened'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_entrance_2
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
      - condition: state
        entity_id: light.inner_candle_entrance
        state: 'off'
      - condition: template
        value_template: >
          '{{ as_timestamp(states.binary_sensor.motion_sensor_entrance_2.last_changed) > as_timestamp(states.binary_sensor.motion_sensor_hallway_2.last_changed) }}'
      - condition: time
        after: '15:00:00'
        before: '23:30:00'
  action:
    - service: light.turn_on
      entity_id: light.inner_candle_entrance

- alias: 'Turn off Entrance after 2 min'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_entrance_2
      to: 'off'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: light.inner_candle_entrance
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.inner_candle_entrance
