- alias: 'Turn on Entrance when door is opened'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_entrance_2
      to: "on"
  condition:
    - condition: template
      value_template: '{{ state_attr("sensor.daylight", "daylight") == "false" }}'
  action:
    - service: light.turn_on
      entity_id: light.inner_candle_entrance
- alias: 'Turn off Entrance after 2 min'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_entrance_2
      to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.motion_sensor_entrance_2
      state: 'pff'
      for:
        minutes: 2
  action:
    - service: light.turn_off
      entity_id: light.inner_candle_entrance