- alias: 'Turn on Cameras when guests open/close door'
  trigger:
    - platform: state
      entity_id: input_boolean.entrance
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.guests
      state: 'on'
  action:
    - alias: Enable Cameras
      service: script.alarm_camera
