- alias: 'Turn on Entrance when hallway triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.hallway
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.asleep
        state: 'off'
  action:
    - service: script.turn_on_entrance

- alias: 'Turn off Entrance after 3 min'
  trigger:
    - platform: state
      entity_id: input_boolean.hallway
      to: 'off'
      for:
        minutes: 3
  action:
    - service: script.turn_off_entrance

- alias: 'Turn off all lights except hallway when hallway goes on and only one person in house'
  trigger:
    - platform: state
      entity_id: input_boolean.hallway
      to: 'on'
  condition:
    - condition:  state
      entity_id: input_boolean.one_person
      state: 'on'
  action:
    - service: script.turn_off_dining
    - service: script.turn_off_bedroom
    - service: script.turn_off_living
    - service: script.turn_off_entrance
    - service: script.turn_off_kitchen
