- alias: 'Turn on Entrance when hallway triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.hallway
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.inner_candle_entrance

- alias: 'Turn off Entrance after 2 min'
  trigger:
    - platform: state
      entity_id: input_boolean.hallway
      to: 'off'
      for:
        minutes: 2
  action:
    - service: light.turn_off
      entity_id: light.inner_candle_entrance
