- alias: 'Turn on Kitchen when sensor triggered'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_kitchen_2
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", true) }}'
      - condition: state
        entity_id: light.hue_bulb_kitchen
        state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.hue_bulb_kitchen

- alias: 'Turn off Kitchen after 2 min'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_kitchen_2
      to: 'off'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: light.hue_bulb_kitchen
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.hue_bulb_kitchen
