- alias: 'Turn on Kitchen when sensor triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.asleep
        state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.hue_bulb_kitchen

- alias: 'Turn off Kitchen after 2 min'
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen
      to: 'off'
      for:
        minutes: 2
  action:
    - service: light.turn_off
      entity_id: light.hue_bulb_kitchen
