- alias: 'Turn on Kitchen when sensor triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.daylight
        state: 'off'
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.asleep
        state: 'off'
  action:
    - service: script.turn_on_kitchen

- alias: 'Turn off Kitchen after 2 min'
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen
      to: 'off'
      for:
        minutes: 2
  action:
    - service: script.turn_off_kitchen

- alias: 'Turn off bedroom when kitchen goes on and only one person in house'
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen
      to: 'on'
  condition:
    - condition:  state
      entity_id: input_boolean.one_person
      state: 'on'
  action:
    - service: script.turn_off_bedroom
