- alias: 'Turn on Living Room when TV is on and it gets dark'
  trigger:
    - platform: template
      value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
  condition:
    - condition: state
      entity_id: media_player.mybraviatv
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hue_colour
        rgb_color: [255,145,38]
        brightness_pct: 100
        transition: 900

- alias: 'Turn on Living Room when TV goes off'
  trigger:
    - platform: state
      entity_id: media_player.mybraviatv
      to: 'off'
  condition:
    - condition: template
      value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
  action:
    - service: homeassistant.turn_on
      entity_id: group.dinning_room
    - delay:
        minutes: 1
    - service: light.turn_off
      entity_id: light.hue_colour
    - delay:
        minutes: 3
    - service: homeassistant.turn_off
      entity_id: group.dinning_room
