- alias: 'Turn on Living Room when TV is on and it gets dark'
  trigger:
    - platform: state
      entity_id: input_boolean.daylight
      state: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.mybraviatv
        state: 'on'
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.asleep
        state: 'off'
  action:
    - condition: state
      entity_id: input_boolean.living_light_override
      state: 'off'
    - service: scene.turn_on
      entity_id: scene.movie_night_light

- alias: 'Turn off Living Room when TV goes off'
  trigger:
    - platform: state
      entity_id: media_player.mybraviatv
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.daylight
        state: 'off'
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'off'
  action:
    - service: script.turn_on_dining
    - delay:
        minutes: 1
    - service: script.turn_off_living
    - delay:
        minutes: 3
    - service: script.turn_off_dining

- alias: 'Turn on Living Room if TV goes on and it is dark'
  trigger:
    - platform: state
      entity_id: media_player.mybraviatv
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.daylight
        state: 'off'
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.asleep
        state: 'off'
  action:
    - condition: state
      entity_id: input_boolean.living_light_override
      state: 'off'
    - service: script.turn_off_dining
    - service: scene.turn_on
      entity_id: scene.movie_night_light