- alias: 'Reminder to take Meter Readings'
  trigger:
    - platform: state
      entity_id: person.tim
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '16:00:00'
        weekday:
          - mon
      - condition: state
        entity_id: input_boolean.meter_notification_sent
        state: 'off'
  action:
    - service: notify.tim_phone_notifier
      data:
        title: "Meter Readings Reminder"
        target: TimsS7
        message: "Reminder to take Elec/Gas/Water readings"
    - service: state
      entity_id: input_boolean.meter_notification_sent
      state: 'on'