- alias: 'Reminder to take Meter Readings'
  trigger:
    - platform: state
      entity_id: person.tim
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '16:00:00'
        weekday:
          - mon
      - condition: state
        entity_id: input_boolean.meter_notification_sent
        state: 'off'
  action:
    - service: notify.mobile_app_tim_mobile
      data:
        title: "Meter Readings Reminder"
        message: "Reminder to take Elec/Gas/Water readings"
    - service: homeassistant.turn_on
      entity_id: input_boolean.meter_notification_sent