- alias: Set Theme
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.daylight
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", true) }}'
      sequence:
      - service: frontend.set_theme
        data:
          name: clear
    - conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
      sequence:
      - service: frontend.set_theme
        data:
          name: midnight-remake