- alias: Set Theme
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: input_boolean.daylight
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.daylight
        state: true
      sequence:
      - service: frontend.set_theme
        data:
          name: clear
    - conditions:
      - condition: state
        entity_id: input_boolean.daylight
        state: false
      sequence:
      - service: frontend.set_theme
        data:
          name: midnight-remake