- alias: 'Switch TV source to HDMI 2 if PS4 is truned on'
  trigger:
    - platform: state
      entity_id: media_player.playstation_4
      from: 'off'
      to: 'idle'
    - platform: state
      entity_id: media_player.playstation_4
      to: 'on'
  action:
    - service: media_player.turn_on
      entity_id: media_player.mybraviatv
    - service: media_player.select_source
      data:
        entity_id: media_player.mybraviatv
        source: 'HDMI 2/MHL'
    - condition: and
      conditions:
        - condition: template
          value_template: '{{ is_state_attr("sensor.daylight", "daylight", true) }}'
    - service: scene.turn_on
      entity_id: scene.movie_night_light
