- alias: 'Switch TV to Netflix when PS4 is turned off'
  trigger:
    - platform: state
      entity_id: media_player.playstation_4
      from: 'on'
      to: 'idle'
    - platform: state
      entity_id: media_player.playstation_4
      to: 'off'
  action:
    - service: media_player.turn_on
      entity_id: media_player.mybraviatv
    - service: media_player.play_media
      data:
        entity_id: media_player.mybraviatv
        media_content_type: tvshow
        media_content_id: 'Netflix'
    - condition: and
      conditions:
        - condition: template
          value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
    - service: scene.turn_on
      entity_id: scene.movie_night_light
