- alias: 'Turn on Hallway when storage sensor triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.storage
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.asleep
        state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: group.hallway

- alias: 'Turn off Hallway after 3 min - Storage trigger'
  trigger:
    - platform: state
      entity_id: input_boolean.storage
      to: 'off'
      for:
        minutes: 3
  action:
    - service: homeassistant.turn_off
      entity_id: group.hallway
