- alias: 'Turn on Hallway when storage sensor triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.storage
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.daylight
        state: false
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.asleep
        state: 'off'
  action:
    - service: script.turn_on_hallway

- alias: 'Turn off Hallway after 3 min - Storage trigger'
  trigger:
    - platform: state
      entity_id: input_boolean.storage
      to: 'off'
      for:
        minutes: 3
  action:
    - service: script.turn_off_hallway
