- alias: 'Toggle entrance boolean when sensor triggers'
  trigger:
    - platform: state
      entity_id: binary_sensor.window_door_sensor_entrance
      to: 'on'
  condition: 
    - condition: template
      value_template: '{{ ( (as_timestamp(states.binary_sensor.window_door_sensor_entrance.last_changed) 
      - (as_timestamp(states.binary_sensor.motion_sensor_hallway.last_changed))) > 0 ) }}'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.entrance

- alias: 'Toggle entrance boolean after 15 sec'
  trigger:
    - platform: state
      entity_id: input_boolean.entrance
      to: 'on'
      for:
        seconds: 30
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.entrance
