- alias: 'Turn off Asleep Boolean in the morning'
  trigger:
    - platform: template
      value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.asleep
