- alias: 'Turn off Asleep Boolean in the morning'
  trigger:
    - platform: template
      value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
    - platform: time
      at: "07:00:00"
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.everyone_asleep