- alias: 'Toggle hallway boolean when sensor triggers'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_hallway
      to: 'on'
  condition: 
    - condition: template
      value_template: '{{ ( (as_timestamp(states.binary_sensor.motion_sensor_hallway.last_changed) 
      - (as_timestamp(states.binary_sensor.openclose_1.last_changed))) > 0 ) }}'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.hallway

- alias: 'Toggle hallway boolean after 15 sec'
  trigger:
    - platform: state
      entity_id: input_boolean.hallway
      to: 'on'
      for:
        seconds: 30
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.hallway