- alias: 'Toggle boolean when everyone leaves home'
  trigger:
    - platform: template
      value_template: '{% if not is_state("person.ruby", "home") and not is_state("person.tim", "home") %}true{% endif %}'
  condition: 
    - condition: state
      entity_id: input_boolean.override_presence
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.no_one_home

- alias: 'Toggle boolean when someone is home'
  trigger:
    - platform: template
      value_template: '{% if is_state("person.ruby", "home") or is_state("person.tim", "home") %}true{% endif %}'
  condition: 
    - condition: state
      entity_id: input_boolean.override_presence
      state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.no_one_home
    - service: homeassistant.turn_on
      entity_id: input_boolean.disable_alarm
    - service: homeassistant.turn_off
      entity_id: input_boolean.cleaner
