- alias: 'Toggle kitchen boolean when sensor triggers'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_kitchen
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.kitchen

- alias: 'Toggle kitchen boolean after 15 sec'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_kitchen
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.kitchen