- alias: 'Turn off Asleep Boolean in the morning'
  trigger:
    - platform: state
      entity_id: input_boolean.daylight
      to: 'on'
    - platform: time
      at: "07:00:00"
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.asleep
