- alias: Toggle Cleaner Boolean ON
  trigger:
    - platform: state
      entity_id: input_boolean.no_one_home
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - wed
      - condition: template
        value_template: "{{ (as_timestamp(now()) | timestamp_custom ('%U') | int % 2) == 0 }}"
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.cleaner

- alias: Toggle Cleaner Boolean OFF
  trigger:
    platform: time
    at: '14:30:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - thu
      - condition: state
        entity_id: input_boolean.cleaner
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.cleaner
