- alias: Toggle Cleaner Boolean
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    - condition: time
      weekday:
        - thu
    - condition: template
      value_template: "{{ (as_timestamp(now()) | timestamp_custom ('%U') | int % 2) == 1 }}"
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.cleaner
