- alias: Toggle Cleaner Boolean ON
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - thu
      - condition: template
        value_template: "{{ (as_timestamp(now()) | timestamp_custom ('%U') | int % 2) == 1 }}"
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.cleaner
    - service: notify.tim_phone_notifier
      data:
        title: "Leave Moeny for Cleaner"
        message: "Don't forget to leave €60 for the cleaner on the table"

- alias: Toggle Cleaner Boolean OFF
  trigger:
    platform: time
    at: '18:30:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - thu
      - condition: state
        entity_id: input_boolean.cleaner
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.cleaner
