- alias: 'Toggle daylight boolean to ON'
  trigger:
    - platform: template
      value_template: '{{ is_state_attr("sensor.daylight", "daylight", true) }}'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.daylight

- alias: 'Toggle daylight boolean to OFF'
  trigger:
    - platform: template
      value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.daylight