- alias: 'Turn on Dining and Hallway when top stairs sensor triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.top_stairs
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ is_state_attr("sensor.daylight", "daylight", false) }}'
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.asleep
        state: 'off'
  action:
    - service: script.turn_on_dining
    - service: script.turn_on_hallway
    - delay:
        minutes: 3
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.window_door_sensor_storage
          state: 'off'
    - service: script.turn_off_hallway
