- alias: 'Turn on Dining and Hallway when top stairs sensor triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.top_stairs
      to: 'on'
  condition:
    - condition: template
      value_template: '{{ is_state_attr("sensor.daylight", "daylight", true) }}'
  action:
    - service: homeassistant.turn_on
      entity_id: group.dinning_room
    - service: light.turn_on
      entity_id: light.hue_bulb_hallway
