- alias: 'Turn on Dining and Hallway when top stairs sensor triggered'
  mode: restart
  trigger:
    - platform: state
      entity_id: input_boolean.top_stairs
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.daylight
        state: false
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.asleep
        state: 'off'
  action:
    - service: script.turn_on_dining
    - service: script.turn_on_hallway
    - delay:
        minutes: 1
    - condition: state
      entity_id: binary_sensor.window_door_sensor_storage
      state: 'off'
    - service: script.turn_off_hallway
    - delay:
        minutes: 2
    - condition: state
      entity_id: media_player.mybraviatv
      state: 'on'
    - service: script.turn_off_dining

- alias: 'Turn off all lights except hallway when hallway goes on and only one person in house'
  trigger:
    - platform: state
      entity_id: input_boolean.top_stairs
      to: 'on'
  condition:
    - condition:  state
      entity_id: input_boolean.one_person
      state: 'on'
  action:
    - service: script.turn_off_bedroom
    - service: script.turn_off_living
    - service: script.turn_off_entrance
    - service: script.turn_off_kitchen
