- alias: Send Notificxation Completed Torrent
  trigger:
    platform: event
    event_type: transmission_downloaded_torrent
  action:
    - service: notify.mobile_app_tim_mobile
      data_template:
        title: "Torrent completed!"
        message: "{{trigger.event.data.name}}"
