- alias: 'Trigger Entrance Automation After Disabling alarm'
  trigger:
    - platform: state
      entity_id: input_boolean.disable_alarm
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ ( (as_timestamp(states.input_boolean.disable_alarm.last_changed) 
        - (as_timestamp(states.input_boolean.entrance.last_changed))) > 0 ) }}'
      - condition: state
        entity_id: input_boolean.daylight
        state: 'off'
  action:
    - alias: Delay for 1 seconds
      delay:
        seconds: 1
    - service: automation.trigger
      entity_id: automation.turn_on_hallway_then_dining_when_entrance_sensor_triggered