- alias: 'Turn off all lights when everyone leaves the house'
  trigger:
    - platform: template
      value_template: '{% if is_state("person.ruby", "not_home") and is_state("person.tim", "not_home") %}'
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_lights