- alias: 'Turn off downstairs if bottom stairs counter is lower than one'
  trigger:
    - platform: state
      entity_id: input_boolean.daylight
      to: 'on'
      for:
        hours: 1
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_lights
