- alias: 'Trigger alarm when unauthorised entrance is triggered'
  trigger:
    - platform: state
      entity_id: input_boolean.entrance
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.no_one_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.disable_alarm
        state: 'off'
  action:
    - alias: Send Notification
      service: script.turn_on
      entity_id: script.alarm_notification
      data:
        variables:
          title: "!!! ENTRANCE HAS BEEN TRIGGERED !!!"
          message: "!!! The front door has been opened !!!"
    - alias: Enable Cameras
      service: script.turn_on
      entity_id: script.alarm_camera
    - alias: Enable Alarm Lights
      service: script.turn_on
      entity_id: script.alarm_lights
    - alias: Delay for 5 seconds
      delay:
        seconds: 5
    - alias: Disable Alarm Lights
      service: script.turn_off
      entity_id: script.alarm_lights
    - alias: Delay for 30 seconds
      delay:
        seconds: 30
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.no_one_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.disable_alarm
          state: 'off'
    - alias: Enable Alarm Lights
      service: script.turn_on
      entity_id: script.alarm_lights
    # - alias: Enable Unauthorised Entrance Voice Alarm
    #   service: script.turn_on
    #   entity_id: script.alarm_voice
    #   data:
    #     variables:
    #       message: "Unauthorised entrance has been detected. Video recording is enabled. The home owner and police have been notified. LEAVE NOW!!"
    # - alias: Delay for 5 minutes
    # - delay:
    #     minutes: 5
    # - alias: Disable Alarm
    #   service: homeassistant.turn_on
    #   entity_id: input_boolean.disable_alarm
