- alias: 'Warn when water sensor is triggered'
  trigger:
    - platform: state
      entity_id: binary_sensor.water_1
      to: 'on'
    - platform: state
      entity_id: binary_sensor.water_2
      to: 'on'
    - platform: state
      entity_id: binary_sensor.water_3
      to: 'on'
    - platform: state
      entity_id: binary_sensor.water_4
      to: 'on'
  action:
    - service: notify.tim_phone_notifier
      data:
        title: "!!! WATER SENSOR WARNING !!!"
        target: TimsS7
        data_template:
          message: '{% if is_state("binary_sensor.water_1", "off") or is_state("binary_sensor.water_4", "on") %}
          !!! Water sensor under the dish weasher has been triggered !!!
          {% elif is_state("binary_sensor.water_2", "on") %}
          !!! Water sensor under the washing machine has been triggered !!!
          {% elif is_state("binary_sensor.water_3", "on") %}
          !!! Water sensor under the boiler has been triggered !!!
          {% endif %}'