- alias: 'Warn when water sensor is triggered'
  trigger:
    # - platform: template
    #   entity_id: '{% if is_state("binary_sensor.water_1", "on") or is_state("binary_sensor.water_2", "on") or is_state("binary_sensor.water_3", "on") or is_state("binary_sensor.water_4", "on") %}true{% endif %}'
    - platform: state
      entity_id: binary_sensor.water_1
      to: 'on'
  action:
    - service: notify.tim_phone_notifier
      title: "!!! WATER SENSOR WARNING !!!"
      target: TimsS7
      message: "!!! Water sensor under the dish weasher has been triggered !!!"
      # data_template:
      #   message: '{% if is_state("binary_sensor.water_1", "on") or is_state("binary_sensor.water_4", "on") %}!!! Water sensor under the dish weasher has been triggered !!!{% elif is_state("binary_sensor.water_2", "on") %}!!! Water sensor under the washing machine has been triggered !!!{% elif is_state("binary_sensor.water_3", "on") %}!!! Water sensor under the boiler has been triggered !!!{% endif %}'