- alias: 'Warn when water sensor is triggered'
  trigger:
    - platform: state
      entity_id: binary_sensor.water_sensor_1
      to: 'on'
    - platform: state
      entity_id: binary_sensor.water_sensor_2
      to: 'on'
    - platform: state
      entity_id: binary_sensor.water_sensor_3
      to: 'on'
    - platform: state
      entity_id: binary_sensor.water_sensor_4
      to: 'on'
  action:
    - alias: Send Notification
      service: script.turn_on
      entity_id: script.alarm_notification
      data:
        title: "!!! WATER SENSOR WARNING !!!"
        message: "{% if is_state('binary_sensor.water_sensor_1', 'on') or is_state('binary_sensor.water_sensor_4', 'on') %}
        !!! Water sensor under the dish washer has been triggered !!!
        {% elif is_state('binary_sensor.water_sensor_2', 'on') %}
        !!! Water sensor under the washing machine has been triggered !!!
        {% elif is_state('binary_sensor.water_sensor_3', 'on') %}
        !!! Water sensor under the boiler has been triggered !!!
        {% endif %}"
    - service: media_player.media_pause
      entity_id: media_player.mybraviatv
    - alias: Voice Alarm
      service: homeassistant.turn_on
      entity_id: script.alarm_voice
      data:
        message: "A water leak has been detected. The
        {% if is_state('binary_sensor.water_sensor_1', 'on') or is_state('binary_sensor.water_sensor_4', 'on') %}
        water sensor under the dish washer has been triggered.
        {% elif is_state('binary_sensor.water_sensor_2', 'on') %}
        water sensor under the washing machine has been triggered.
        {% elif is_state('binary_sensor.water_sensor_3', 'on') %}
        water sensor under the boiler has been triggered.
        {% endif %}"
